"""Generate sidelobes.js: range-sidelobe envelopes of a compressed LFM pulse.

    uv run python mission_design_tool/build_sidelobes.py

When the bed echo falls inside the transmitted pulse, the compressed surface
return leaves a sidelobe pedestal at the bed's delay. Its level depends on two
dimensionless numbers — the time-bandwidth product TB = B*tau and the normalised
delay x = dt/tau — and on the receive weighting.

Rectangular has the closed form -20 log10(pi*B*dt), but it is 10-15 dB
pessimistic as x approaches 1, and Hann has no comparably simple form (at fixed
B*dt its level still varies ~20 dB with tau). So both are tabulated here from a
direct matched-filter simulation and shipped as a lookup, which keeps one code
path and one validated source of truth.
"""

import json
from pathlib import Path

import numpy as np
from scipy.signal import fftconvolve

OUT = Path(__file__).parent / "sidelobes.js"
TB_GRID = np.geomspace(10, 1e5, 22)
X_GRID = np.concatenate([[0.0], np.geomspace(2e-4, 1.0, 47)])

# SNR cost of the receive weighting itself: (mean w)^2 / mean(w^2).
WEIGHTING_LOSS = {"rect": 0.0, "hann": 1.76}


def envelope(TB: float, window: str) -> np.ndarray:
    """Sidelobe level [dB below peak] at each x, for one time-bandwidth product."""
    n = int(TB * 8)                                  # 8x oversampled
    t = (np.arange(n) - n / 2) / n                   # tau = 1
    s = np.exp(1j * np.pi * TB * t * t)              # LFM sweeping B = TB over tau
    w = np.hanning(n) if window == "hann" else np.ones(n)
    y = np.abs(fftconvolve(s, np.conj(s[::-1]) * w)) ** 2
    y /= y.max()
    c = len(y) // 2
    lag = (np.arange(len(y)) - c) / n

    out = []
    for x in X_GRID:
        if x <= 0:
            out.append(0.0)
            continue
        i = int(np.searchsorted(lag, x))
        if i >= len(y) - 3:
            out.append(-200.0)                       # past the pulse: no response
            continue
        # local maximum, so landing in a null does not understate the pedestal
        out.append(10 * np.log10(max(y[max(0, i - 4):i + 5].max(), 1e-20)))
    return np.array(out)


def main():
    tables = {}
    for window in ("rect", "hann"):
        tables[window] = np.array([envelope(tb, window) for tb in TB_GRID])
        print(f"{window}: {tables[window].shape}, "
              f"{tables[window].min():.0f} to {tables[window].max():.0f} dB")

    body = f"""// GENERATED by build_sidelobes.py — do not edit by hand.
//
// Range-sidelobe level of a compressed LFM, as dB below the peak, tabulated
// against the time-bandwidth product TB = B*tau and the normalised delay
// x = dt/tau. Both windows come from a direct matched-filter simulation; see
// build_sidelobes.py for why neither is used in closed form.

/** SNR cost of the receive weighting itself, (mean w)^2 / mean(w^2). */
export const WEIGHTING_LOSS_dB = {json.dumps(WEIGHTING_LOSS)};

const TB = {json.dumps([round(float(v), 4) for v in TB_GRID])};
const X = {json.dumps([round(float(v), 6) for v in X_GRID])};
const TABLE = {{
{"".join(f'  {w}: {json.dumps([[round(float(v), 1) for v in r] for r in t])},{chr(10)}' for w, t in tables.items())}}};

const span = (grid, v) => {{
  let i = 0;
  while (i < grid.length - 2 && grid[i + 1] < v) i++;
  return i;
}};

/**
 * Sidelobe level [dB, negative] of the compressed surface return at a delay of
 * `x = dt/tau` behind its peak, for time-bandwidth product `tb`.
 * Returns -Infinity past the pulse, where the matched filter has no support.
 */
export function sidelobeLevel(window, tb, x) {{
  const t = TABLE[window] || TABLE.rect;
  if (!(x > 0)) return 0;                 // at the peak itself
  if (x >= 1) return -Infinity;
  const i = span(TB, tb), j = span(X, x);
  const fi = Math.min(1, Math.max(0,
    (Math.log(tb) - Math.log(TB[i])) / (Math.log(TB[i + 1]) - Math.log(TB[i]))));
  const fj = Math.min(1, Math.max(0, (x - X[j]) / (X[j + 1] - X[j])));
  return (1 - fi) * (1 - fj) * t[i][j] + fi * (1 - fj) * t[i + 1][j]
       + (1 - fi) * fj * t[i][j + 1] + fi * fj * t[i + 1][j + 1];
}}
"""
    OUT.write_text(body)
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.1f} kB)")


if __name__ == "__main__":
    main()
